#a=input("enter your name :")
#print("My name is",a)
a=int(input("Enter number 1st :"))
b=int(input("Enter number 2nd :"))
print("the value of ",a,"+",b,"is",a+b)
print("the value of ",a,"-",b,"is",a-b)
print("the value of ",a,"*",b,"is",a*b)
print("the value of ",a,"**",b,"is",a**b)
print("the value of ",a,"/",b,"is",a/b)
print("the value of ",a,"%",b,"is",a%b)
